### ISSUE TITLE
 Problems sending a string from kernel to a program

### ISSUE THREAD

**Issue by ronnyvillamar99** [thrimbor/frost#1]
I'm working on your project, but I have some problems
I can not send a pointer from kernel to a thread or program, it throws me an exception

**Comment by ronnyvillamar99** [comment]
I am working this through interruptions

**Comment by thrimbor** [comment]
I'm not entirely sure I get what you're trying to do.

Are you trying to pass a string by passing a pointer to the content to a userspace process? If so, this won't work, since this pointer will point to kernel memory which is protected from userspace access for security reasons.

The proper way to do this would be to reserve memory in the userspace process and pass a pointer to it to the kernel, which then can copy content into this buffer. However, the kernel would then have to check whether this pointer is safe to use (Linux has special copy-functions that check for this: copy_from_user and copy_to_user) - this is something the current syscall-implementations do not do, which is a major security issue which has to get tackled in the future.

If this is not what you're trying to accomplish, please provide additional information about what exactly you're trying to do, what did happen and what you expected to happen.

**Comment by ronnyvillamar99** [comment]
Thanks, if it was what I wanted to clarify, I'll investigate about it.

**Comment by ronnyvillamar99** [comment]
What I was trying to implement was that through a syscall send data from strings, such as the name of the cpu or some other things

**Comment by thrimbor** [comment]
You haven't provided any more details on what precisely your code does, but judging from your description so far I'm assuming you're hitting the expected behavior I described above. Since that is not a bug, I'm closing this issue.
